/*
=============================================================================
VIGIL Risk Planning - Table DDL
=============================================================================
Script 2: Create all tables in ATOMIC schema

Run after 01_create_database.sql
=============================================================================
*/

USE DATABASE RISK_PLANNING_DB;
USE SCHEMA ATOMIC;
USE WAREHOUSE RISK_COMPUTE_WH;

-- =====================
-- LOCATION TABLE
-- =====================
CREATE OR REPLACE TABLE LOCATION (
    LOCATION_ID VARCHAR(50) PRIMARY KEY,
    REGION VARCHAR(50) NOT NULL,
    COUNTY VARCHAR(100),
    CITY VARCHAR(100),
    ZIP_CODE VARCHAR(10),
    LATITUDE FLOAT NOT NULL,
    LONGITUDE FLOAT NOT NULL,
    ELEVATION_FT FLOAT,
    TERRAIN_TYPE VARCHAR(50),
    LAND_USE VARCHAR(50),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Geographic locations for assets and circuits';

-- =====================
-- CIRCUIT TABLE
-- =====================
CREATE OR REPLACE TABLE CIRCUIT (
    CIRCUIT_ID VARCHAR(50) PRIMARY KEY,
    CIRCUIT_NAME VARCHAR(100) NOT NULL,
    VOLTAGE_CLASS VARCHAR(50) NOT NULL,
    FIRE_THREAT_DISTRICT VARCHAR(20) NOT NULL,
    PRIMARY_LOCATION_ID VARCHAR(50) REFERENCES LOCATION(LOCATION_ID),
    TOTAL_CUSTOMERS INTEGER DEFAULT 0,
    CRITICAL_FACILITIES INTEGER DEFAULT 0,
    MEDICAL_BASELINE_CUSTOMERS INTEGER DEFAULT 0,
    CIRCUIT_MILES FLOAT,
    SUBSTATION_NAME VARCHAR(100),
    PSPS_ELIGIBLE BOOLEAN DEFAULT FALSE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Electrical circuits with fire threat district classification';

-- =====================
-- ASSET TABLE
-- =====================
CREATE OR REPLACE TABLE ASSET (
    ASSET_ID VARCHAR(50) PRIMARY KEY,
    CIRCUIT_ID VARCHAR(50) REFERENCES CIRCUIT(CIRCUIT_ID),
    LOCATION_ID VARCHAR(50) REFERENCES LOCATION(LOCATION_ID),
    ASSET_TYPE VARCHAR(50) NOT NULL,
    ASSET_SUBTYPE VARCHAR(50),
    MATERIAL VARCHAR(50),
    MANUFACTURER VARCHAR(100),
    MODEL_NUMBER VARCHAR(100),
    VOLTAGE_CLASS VARCHAR(50),
    INSTALLATION_DATE DATE,
    ASSET_AGE_YEARS FLOAT,
    CONDITION_SCORE FLOAT,
    LAST_INSPECTION_DATE DATE,
    NEXT_INSPECTION_DUE DATE,
    INSPECTION_CYCLE_MONTHS INTEGER DEFAULT 12,
    REPLACEMENT_COST FLOAT,
    MOISTURE_EXPOSURE VARCHAR(20),
    WIND_EXPOSURE VARCHAR(20),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Utility assets including poles, transformers, conductors, and underground cables';

-- =====================
-- VEGETATION ENCROACHMENT TABLE
-- =====================
CREATE OR REPLACE TABLE VEGETATION_ENCROACHMENT (
    ENCROACHMENT_ID VARCHAR(50) PRIMARY KEY,
    ASSET_ID VARCHAR(50) REFERENCES ASSET(ASSET_ID),
    SPECIES VARCHAR(100),
    CURRENT_CLEARANCE_FT FLOAT NOT NULL,
    REQUIRED_CLEARANCE_FT FLOAT NOT NULL,
    CLEARANCE_DEFICIT_FT FLOAT GENERATED ALWAYS AS (REQUIRED_CLEARANCE_FT - CURRENT_CLEARANCE_FT) VIRTUAL,
    GROWTH_RATE_FT_YEAR FLOAT,
    DAYS_TO_CONTACT INTEGER,
    TREE_HEIGHT_FT FLOAT,
    TREE_HEALTH VARCHAR(20),
    TRIM_PRIORITY VARCHAR(20),
    LAST_TRIM_DATE DATE,
    NEXT_TRIM_DUE DATE,
    ESTIMATED_TRIM_COST FLOAT,
    SURVEY_DATE DATE,
    SURVEYOR_ID VARCHAR(50),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Vegetation encroachment measurements and GO95 compliance status';

-- =====================
-- RISK ASSESSMENT TABLE
-- =====================
CREATE OR REPLACE TABLE RISK_ASSESSMENT (
    ASSESSMENT_ID VARCHAR(50) PRIMARY KEY,
    ASSET_ID VARCHAR(50) REFERENCES ASSET(ASSET_ID),
    ASSESSMENT_DATE DATE NOT NULL,
    FIRE_RISK_SCORE FLOAT,
    IGNITION_PROBABILITY FLOAT,
    CONSEQUENCE_SCORE FLOAT,
    WIND_EXPOSURE_FACTOR FLOAT,
    FUEL_LOAD_FACTOR FLOAT,
    TERRAIN_FACTOR FLOAT,
    ACCESS_DIFFICULTY_FACTOR FLOAT,
    COMPOSITE_RISK_SCORE FLOAT,
    RISK_TIER VARCHAR(20),
    ASSESSED_BY VARCHAR(100),
    ASSESSMENT_METHOD VARCHAR(50),
    NOTES TEXT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Fire risk assessments with multi-factor scoring';

-- =====================
-- WORK ORDER TABLE
-- =====================
CREATE OR REPLACE TABLE WORK_ORDER (
    WORK_ORDER_ID VARCHAR(50) PRIMARY KEY,
    ASSET_ID VARCHAR(50) REFERENCES ASSET(ASSET_ID),
    WORK_ORDER_TYPE VARCHAR(50) NOT NULL,
    PRIORITY VARCHAR(20) NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    DESCRIPTION TEXT,
    ESTIMATED_COST FLOAT,
    ACTUAL_COST FLOAT,
    SCHEDULED_DATE DATE,
    STARTED_DATE DATE,
    COMPLETED_DATE DATE,
    ASSIGNED_CREW VARCHAR(100),
    CREATED_BY VARCHAR(100),
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Work orders for vegetation management, asset replacement, and maintenance';

-- =====================
-- AMI READING TABLE (For Water Treeing Detection)
-- =====================
CREATE OR REPLACE TABLE AMI_READING (
    READING_ID VARCHAR(50) PRIMARY KEY,
    ASSET_ID VARCHAR(50) REFERENCES ASSET(ASSET_ID),
    METER_ID VARCHAR(50),
    READING_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    VOLTAGE_READING FLOAT,
    VOLTAGE_DIP_FLAG BOOLEAN DEFAULT FALSE,
    VOLTAGE_DIP_MAGNITUDE FLOAT,
    CURRENT_READING FLOAT,
    POWER_FACTOR FLOAT,
    RAINFALL_24H_INCHES FLOAT,
    RAIN_CORRELATED_DIP BOOLEAN DEFAULT FALSE,
    TEMPERATURE_F FLOAT,
    HUMIDITY_PCT FLOAT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'AMI (Advanced Metering Infrastructure) readings for voltage analysis';

-- =====================
-- WEATHER DATA TABLE
-- =====================
CREATE OR REPLACE TABLE WEATHER_DATA (
    WEATHER_ID VARCHAR(50) PRIMARY KEY,
    LOCATION_ID VARCHAR(50) REFERENCES LOCATION(LOCATION_ID),
    OBSERVATION_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    TEMPERATURE_F FLOAT,
    HUMIDITY_PCT FLOAT,
    WIND_SPEED_MPH FLOAT,
    WIND_GUST_MPH FLOAT,
    WIND_DIRECTION VARCHAR(10),
    PRECIPITATION_INCHES FLOAT,
    FIRE_WEATHER_INDEX FLOAT,
    RED_FLAG_WARNING BOOLEAN DEFAULT FALSE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Weather observations for fire risk assessment';

-- =====================
-- ML SCHEMA TABLES
-- =====================
USE SCHEMA ML;

CREATE OR REPLACE TABLE ASSET_HEALTH_PREDICTION (
    PREDICTION_ID VARCHAR(50) PRIMARY KEY,
    ASSET_ID VARCHAR(50),
    PREDICTION_DATE DATE NOT NULL,
    PREDICTED_HEALTH_SCORE FLOAT,
    CONFIDENCE_INTERVAL_LOW FLOAT,
    CONFIDENCE_INTERVAL_HIGH FLOAT,
    DAYS_TO_CRITICAL INTEGER,
    MODEL_VERSION VARCHAR(50),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'ML predictions for asset health degradation';

CREATE OR REPLACE TABLE VEGETATION_GROWTH_PREDICTION (
    PREDICTION_ID VARCHAR(50) PRIMARY KEY,
    ENCROACHMENT_ID VARCHAR(50),
    PREDICTION_DATE DATE NOT NULL,
    PREDICTED_GROWTH_FT FLOAT,
    PREDICTED_DAYS_TO_CONTACT INTEGER,
    SEASONAL_FACTOR FLOAT,
    MODEL_VERSION VARCHAR(50),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'ML predictions for vegetation growth rates';

CREATE OR REPLACE TABLE IGNITION_RISK_PREDICTION (
    PREDICTION_ID VARCHAR(50) PRIMARY KEY,
    ASSET_ID VARCHAR(50),
    PREDICTION_DATE DATE NOT NULL,
    IGNITION_PROBABILITY FLOAT,
    RISK_TIER VARCHAR(20),
    TOP_RISK_FACTORS VARIANT,
    MODEL_VERSION VARCHAR(50),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'ML predictions for ignition risk probability';

CREATE OR REPLACE TABLE CABLE_FAILURE_PREDICTION (
    PREDICTION_ID VARCHAR(50) PRIMARY KEY,
    ASSET_ID VARCHAR(50),
    PREDICTION_DATE DATE NOT NULL,
    CABLE_AGE_YEARS FLOAT,
    MATERIAL VARCHAR(50),
    MOISTURE_EXPOSURE VARCHAR(20),
    VOLTAGE_DIP_COUNT INTEGER,
    RAIN_CORRELATION_SCORE FLOAT,
    FAILURE_PROBABILITY FLOAT,
    RISK_TIER VARCHAR(20),
    CUSTOMER_IMPACT_COUNT INTEGER,
    ESTIMATED_REPLACEMENT_COST FLOAT,
    MODEL_VERSION VARCHAR(50),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'ML predictions for underground cable failure (Water Treeing detection)';

-- =====================
-- DOCS SCHEMA TABLE
-- =====================
USE SCHEMA DOCS;

CREATE OR REPLACE TABLE GO95_DOCUMENTS (
    DOC_ID VARCHAR(50) PRIMARY KEY,
    DOCUMENT_NAME VARCHAR(200),
    SECTION_NUMBER VARCHAR(50),
    SECTION_TITLE VARCHAR(200),
    CONTENT TEXT,
    VOLTAGE_CLASS VARCHAR(50),
    FIRE_THREAT_DISTRICT VARCHAR(20),
    CLEARANCE_REQUIREMENT_FT FLOAT,
    EFFECTIVE_DATE DATE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'CPUC GO95 regulation documents for Cortex Search';

CREATE OR REPLACE TABLE VEGETATION_PROCEDURES (
    DOC_ID VARCHAR(50) PRIMARY KEY,
    PROCEDURE_NAME VARCHAR(200),
    SPECIES VARCHAR(100),
    PROCEDURE_TYPE VARCHAR(50),
    CONTENT TEXT,
    SAFETY_REQUIREMENTS TEXT,
    EQUIPMENT_NEEDED TEXT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Vegetation management procedures for Cortex Search';

SELECT 'Table DDL complete!' AS STATUS;
