/*
=============================================================================
VIGIL Risk Planning - Sample Data Generation
=============================================================================
Script 3: Generate 5,000 assets across 5 regions with realistic data

Run after 02_create_tables.sql
=============================================================================
*/

USE DATABASE RISK_PLANNING_DB;
USE SCHEMA ATOMIC;
USE WAREHOUSE RISK_COMPUTE_WH;

-- =====================
-- REGION CONFIGURATION
-- =====================
-- NorCal: Northern California (San Francisco to Redding)
-- SoCal: Southern California (Los Angeles, San Diego)
-- PNW: Pacific Northwest (Oregon, Washington)
-- Southwest: Arizona, Nevada
-- Mountain: Colorado, Utah

-- =====================
-- GENERATE LOCATIONS (1000 locations)
-- =====================
CREATE OR REPLACE TEMPORARY TABLE REGION_CONFIG AS
SELECT * FROM VALUES
    ('NorCal', 38.5, -121.5, 2.0, 1.5, ARRAY_CONSTRUCT('Alameda', 'Contra Costa', 'Sacramento', 'Placer', 'Butte', 'Shasta')),
    ('SoCal', 34.0, -117.5, 1.5, 2.0, ARRAY_CONSTRUCT('Los Angeles', 'Orange', 'San Diego', 'Riverside', 'San Bernardino', 'Ventura')),
    ('PNW', 45.5, -122.5, 2.0, 1.0, ARRAY_CONSTRUCT('Multnomah', 'Washington', 'Clackamas', 'Lane', 'Marion', 'Clark')),
    ('Southwest', 33.5, -111.5, 1.5, 2.0, ARRAY_CONSTRUCT('Maricopa', 'Pima', 'Pinal', 'Yavapai', 'Coconino', 'Mohave')),
    ('Mountain', 39.5, -105.5, 2.0, 1.5, ARRAY_CONSTRUCT('Denver', 'Jefferson', 'Boulder', 'Larimer', 'El Paso', 'Arapahoe'))
AS t(REGION, CENTER_LAT, CENTER_LON, LAT_SPREAD, LON_SPREAD, COUNTIES);

INSERT INTO LOCATION (LOCATION_ID, REGION, COUNTY, LATITUDE, LONGITUDE, ELEVATION_FT, TERRAIN_TYPE, LAND_USE)
SELECT
    'LOC-' || LPAD(SEQ4()::VARCHAR, 6, '0') AS LOCATION_ID,
    rc.REGION,
    rc.COUNTIES[MOD(SEQ4(), ARRAY_SIZE(rc.COUNTIES))]::VARCHAR AS COUNTY,
    rc.CENTER_LAT + (RANDOM() - 0.5) * rc.LAT_SPREAD AS LATITUDE,
    rc.CENTER_LON + (RANDOM() - 0.5) * rc.LON_SPREAD AS LONGITUDE,
    CASE rc.REGION
        WHEN 'Mountain' THEN 5000 + RANDOM() * 5000
        WHEN 'PNW' THEN 100 + RANDOM() * 2000
        ELSE 100 + RANDOM() * 3000
    END AS ELEVATION_FT,
    CASE MOD(SEQ4(), 5)
        WHEN 0 THEN 'FLAT'
        WHEN 1 THEN 'HILLY'
        WHEN 2 THEN 'MOUNTAINOUS'
        WHEN 3 THEN 'CANYON'
        ELSE 'COASTAL'
    END AS TERRAIN_TYPE,
    CASE MOD(SEQ4(), 6)
        WHEN 0 THEN 'RESIDENTIAL'
        WHEN 1 THEN 'COMMERCIAL'
        WHEN 2 THEN 'INDUSTRIAL'
        WHEN 3 THEN 'AGRICULTURAL'
        WHEN 4 THEN 'WILDLAND'
        ELSE 'URBAN_INTERFACE'
    END AS LAND_USE
FROM TABLE(GENERATOR(ROWCOUNT => 200)) g
CROSS JOIN REGION_CONFIG rc;

-- =====================
-- GENERATE CIRCUITS (250 circuits, 50 per region)
-- =====================
INSERT INTO CIRCUIT (
    CIRCUIT_ID, CIRCUIT_NAME, VOLTAGE_CLASS, FIRE_THREAT_DISTRICT,
    PRIMARY_LOCATION_ID, TOTAL_CUSTOMERS, CRITICAL_FACILITIES,
    MEDICAL_BASELINE_CUSTOMERS, CIRCUIT_MILES, SUBSTATION_NAME, PSPS_ELIGIBLE
)
SELECT
    'CKT-' || LPAD(ROW_NUMBER() OVER (ORDER BY l.REGION, RANDOM())::VARCHAR, 5, '0') AS CIRCUIT_ID,
    l.REGION || '-' || l.COUNTY || '-' || LPAD(ROW_NUMBER() OVER (PARTITION BY l.REGION ORDER BY RANDOM())::VARCHAR, 3, '0') AS CIRCUIT_NAME,
    CASE MOD(ROW_NUMBER() OVER (ORDER BY RANDOM()), 4)
        WHEN 0 THEN 'LOW_VOLTAGE'
        WHEN 1 THEN 'MEDIUM_VOLTAGE'
        WHEN 2 THEN 'HIGH_VOLTAGE'
        ELSE 'TRANSMISSION'
    END AS VOLTAGE_CLASS,
    CASE 
        WHEN l.LAND_USE IN ('WILDLAND', 'URBAN_INTERFACE') AND l.REGION IN ('NorCal', 'SoCal') THEN
            CASE MOD(ROW_NUMBER() OVER (ORDER BY RANDOM()), 3)
                WHEN 0 THEN 'TIER_3'
                WHEN 1 THEN 'TIER_2'
                ELSE 'TIER_1'
            END
        WHEN l.REGION IN ('NorCal', 'SoCal') THEN
            CASE MOD(ROW_NUMBER() OVER (ORDER BY RANDOM()), 4)
                WHEN 0 THEN 'TIER_2'
                WHEN 1 THEN 'TIER_1'
                ELSE 'NON_HFTD'
            END
        ELSE 'NON_HFTD'
    END AS FIRE_THREAT_DISTRICT,
    l.LOCATION_ID AS PRIMARY_LOCATION_ID,
    FLOOR(500 + RANDOM() * 9500)::INTEGER AS TOTAL_CUSTOMERS,
    FLOOR(RANDOM() * 20)::INTEGER AS CRITICAL_FACILITIES,
    FLOOR(RANDOM() * 100)::INTEGER AS MEDICAL_BASELINE_CUSTOMERS,
    ROUND(5 + RANDOM() * 45, 1) AS CIRCUIT_MILES,
    l.REGION || ' Substation ' || LPAD(MOD(ROW_NUMBER() OVER (ORDER BY RANDOM()), 20)::VARCHAR, 2, '0') AS SUBSTATION_NAME,
    CASE WHEN MOD(ROW_NUMBER() OVER (ORDER BY RANDOM()), 3) = 0 THEN TRUE ELSE FALSE END AS PSPS_ELIGIBLE
FROM LOCATION l
QUALIFY ROW_NUMBER() OVER (PARTITION BY l.REGION ORDER BY RANDOM()) <= 50;

-- Update PSPS_ELIGIBLE based on fire threat district
UPDATE CIRCUIT 
SET PSPS_ELIGIBLE = TRUE 
WHERE FIRE_THREAT_DISTRICT IN ('TIER_2', 'TIER_3');

-- =====================
-- GENERATE ASSETS (5000 assets)
-- =====================
CREATE OR REPLACE TEMPORARY TABLE ASSET_TYPES AS
SELECT * FROM VALUES
    ('POLE', ARRAY_CONSTRUCT('WOOD', 'STEEL', 'COMPOSITE', 'CONCRETE'), 0.20),
    ('TRANSFORMER', ARRAY_CONSTRUCT('PAD_MOUNT', 'POLE_MOUNT', 'SUBMERSIBLE'), 0.15),
    ('CONDUCTOR', ARRAY_CONSTRUCT('ALUMINUM', 'COPPER', 'ACSR'), 0.25),
    ('UNDERGROUND_CABLE', ARRAY_CONSTRUCT('XLPE', 'EPR', 'PILC'), 0.15),
    ('SWITCH', ARRAY_CONSTRUCT('MANUAL', 'AUTOMATED', 'RECLOSER'), 0.10),
    ('FUSE', ARRAY_CONSTRUCT('EXPULSION', 'CURRENT_LIMITING'), 0.08),
    ('CAPACITOR', ARRAY_CONSTRUCT('FIXED', 'SWITCHED'), 0.07)
AS t(ASSET_TYPE, MATERIALS, PROPORTION);

INSERT INTO ASSET (
    ASSET_ID, CIRCUIT_ID, LOCATION_ID, ASSET_TYPE, MATERIAL, VOLTAGE_CLASS,
    INSTALLATION_DATE, ASSET_AGE_YEARS, CONDITION_SCORE,
    LAST_INSPECTION_DATE, NEXT_INSPECTION_DUE, INSPECTION_CYCLE_MONTHS,
    REPLACEMENT_COST, MOISTURE_EXPOSURE, WIND_EXPOSURE
)
SELECT
    'AST-' || LPAD(ROW_NUMBER() OVER (ORDER BY c.CIRCUIT_ID, RANDOM())::VARCHAR, 6, '0') AS ASSET_ID,
    c.CIRCUIT_ID,
    l.LOCATION_ID,
    at.ASSET_TYPE,
    at.MATERIALS[MOD(SEQ4(), ARRAY_SIZE(at.MATERIALS))]::VARCHAR AS MATERIAL,
    c.VOLTAGE_CLASS,
    DATEADD('year', -FLOOR(RANDOM() * 40), CURRENT_DATE()) AS INSTALLATION_DATE,
    FLOOR(RANDOM() * 40) AS ASSET_AGE_YEARS,
    ROUND(0.3 + RANDOM() * 0.7, 2) AS CONDITION_SCORE,
    DATEADD('month', -FLOOR(RANDOM() * 24), CURRENT_DATE()) AS LAST_INSPECTION_DATE,
    DATEADD('month', FLOOR(RANDOM() * 12), CURRENT_DATE()) AS NEXT_INSPECTION_DUE,
    CASE WHEN c.FIRE_THREAT_DISTRICT IN ('TIER_2', 'TIER_3') THEN 6 ELSE 12 END AS INSPECTION_CYCLE_MONTHS,
    CASE at.ASSET_TYPE
        WHEN 'POLE' THEN 5000 + RANDOM() * 15000
        WHEN 'TRANSFORMER' THEN 20000 + RANDOM() * 80000
        WHEN 'CONDUCTOR' THEN 10000 + RANDOM() * 40000
        WHEN 'UNDERGROUND_CABLE' THEN 50000 + RANDOM() * 150000
        WHEN 'SWITCH' THEN 15000 + RANDOM() * 35000
        WHEN 'FUSE' THEN 500 + RANDOM() * 2000
        WHEN 'CAPACITOR' THEN 10000 + RANDOM() * 30000
    END AS REPLACEMENT_COST,
    CASE MOD(SEQ4(), 3)
        WHEN 0 THEN 'LOW'
        WHEN 1 THEN 'MEDIUM'
        ELSE 'HIGH'
    END AS MOISTURE_EXPOSURE,
    CASE 
        WHEN l.TERRAIN_TYPE IN ('MOUNTAINOUS', 'CANYON', 'COASTAL') THEN 'HIGH'
        WHEN l.TERRAIN_TYPE = 'HILLY' THEN 'MEDIUM'
        ELSE 'LOW'
    END AS WIND_EXPOSURE
FROM CIRCUIT c
JOIN LOCATION l ON l.REGION = SPLIT_PART(c.CIRCUIT_NAME, '-', 1)
CROSS JOIN ASSET_TYPES at
CROSS JOIN TABLE(GENERATOR(ROWCOUNT => 20)) g
WHERE RANDOM() < at.PROPORTION * 5
QUALIFY ROW_NUMBER() OVER (ORDER BY RANDOM()) <= 5000;

-- Adjust condition scores based on age (older = worse condition)
UPDATE ASSET
SET CONDITION_SCORE = GREATEST(0.1, CONDITION_SCORE - (ASSET_AGE_YEARS / 100))
WHERE ASSET_AGE_YEARS > 20;

-- =====================
-- GENERATE VEGETATION ENCROACHMENTS
-- =====================
CREATE OR REPLACE TEMPORARY TABLE TREE_SPECIES AS
SELECT * FROM VALUES
    ('EUCALYPTUS', 6.0, 'EXTREME'),
    ('OAK', 2.0, 'MODERATE'),
    ('PINE', 3.0, 'HIGH'),
    ('PALM', 1.5, 'HIGH'),
    ('WILLOW', 4.0, 'LOW'),
    ('CYPRESS', 2.5, 'HIGH'),
    ('MANZANITA', 1.0, 'EXTREME'),
    ('REDWOOD', 2.0, 'MODERATE'),
    ('JUNIPER', 1.5, 'HIGH'),
    ('COTTONWOOD', 3.5, 'MODERATE')
AS t(SPECIES, GROWTH_RATE, FIRE_RISK);

INSERT INTO VEGETATION_ENCROACHMENT (
    ENCROACHMENT_ID, ASSET_ID, SPECIES, CURRENT_CLEARANCE_FT, REQUIRED_CLEARANCE_FT,
    GROWTH_RATE_FT_YEAR, DAYS_TO_CONTACT, TREE_HEIGHT_FT, TREE_HEALTH,
    TRIM_PRIORITY, LAST_TRIM_DATE, NEXT_TRIM_DUE, ESTIMATED_TRIM_COST, SURVEY_DATE
)
SELECT
    'VEG-' || LPAD(ROW_NUMBER() OVER (ORDER BY a.ASSET_ID, RANDOM())::VARCHAR, 6, '0') AS ENCROACHMENT_ID,
    a.ASSET_ID,
    ts.SPECIES,
    ROUND(RANDOM() * 15, 1) AS CURRENT_CLEARANCE_FT,
    CASE 
        WHEN c.FIRE_THREAT_DISTRICT = 'TIER_3' THEN
            CASE a.VOLTAGE_CLASS
                WHEN 'LOW_VOLTAGE' THEN 4.0
                WHEN 'MEDIUM_VOLTAGE' THEN 6.0
                WHEN 'HIGH_VOLTAGE' THEN 12.0
                ELSE 15.0
            END
        WHEN c.FIRE_THREAT_DISTRICT = 'TIER_2' THEN
            CASE a.VOLTAGE_CLASS
                WHEN 'LOW_VOLTAGE' THEN 4.0
                WHEN 'MEDIUM_VOLTAGE' THEN 4.0
                WHEN 'HIGH_VOLTAGE' THEN 6.0
                ELSE 10.0
            END
        ELSE
            CASE a.VOLTAGE_CLASS
                WHEN 'LOW_VOLTAGE' THEN 2.5
                WHEN 'MEDIUM_VOLTAGE' THEN 4.0
                WHEN 'HIGH_VOLTAGE' THEN 4.0
                ELSE 10.0
            END
    END AS REQUIRED_CLEARANCE_FT,
    ts.GROWTH_RATE AS GROWTH_RATE_FT_YEAR,
    NULL AS DAYS_TO_CONTACT,  -- Will calculate below
    ROUND(20 + RANDOM() * 80, 0) AS TREE_HEIGHT_FT,
    CASE MOD(SEQ4(), 4)
        WHEN 0 THEN 'HEALTHY'
        WHEN 1 THEN 'FAIR'
        WHEN 2 THEN 'POOR'
        ELSE 'DEAD'
    END AS TREE_HEALTH,
    NULL AS TRIM_PRIORITY,  -- Will calculate below
    DATEADD('month', -FLOOR(RANDOM() * 36), CURRENT_DATE()) AS LAST_TRIM_DATE,
    DATEADD('month', FLOOR(RANDOM() * 18), CURRENT_DATE()) AS NEXT_TRIM_DUE,
    ROUND(500 + RANDOM() * 2500, 0) AS ESTIMATED_TRIM_COST,
    DATEADD('day', -FLOOR(RANDOM() * 90), CURRENT_DATE()) AS SURVEY_DATE
FROM ASSET a
JOIN CIRCUIT c ON a.CIRCUIT_ID = c.CIRCUIT_ID
CROSS JOIN TREE_SPECIES ts
WHERE a.ASSET_TYPE IN ('POLE', 'CONDUCTOR')
AND RANDOM() < 0.4
QUALIFY ROW_NUMBER() OVER (PARTITION BY a.ASSET_ID ORDER BY RANDOM()) <= 2;

-- Calculate DAYS_TO_CONTACT
UPDATE VEGETATION_ENCROACHMENT
SET DAYS_TO_CONTACT = 
    CASE 
        WHEN CURRENT_CLEARANCE_FT <= REQUIRED_CLEARANCE_FT THEN 0
        WHEN GROWTH_RATE_FT_YEAR > 0 THEN 
            FLOOR((CURRENT_CLEARANCE_FT - REQUIRED_CLEARANCE_FT) / GROWTH_RATE_FT_YEAR * 365)
        ELSE 9999
    END;

-- Calculate TRIM_PRIORITY
UPDATE VEGETATION_ENCROACHMENT v
SET TRIM_PRIORITY = 
    CASE 
        WHEN v.DAYS_TO_CONTACT <= 30 OR v.CURRENT_CLEARANCE_FT < v.REQUIRED_CLEARANCE_FT THEN 'CRITICAL'
        WHEN v.DAYS_TO_CONTACT <= 90 THEN 'HIGH'
        WHEN v.DAYS_TO_CONTACT <= 180 THEN 'MEDIUM'
        ELSE 'LOW'
    END;

SELECT 'Sample data generation complete - Part 1!' AS STATUS;
