/*
=============================================================================
VIGIL Risk Planning - Sample Data Generation Part 2
=============================================================================
Script 4: Generate Risk Assessments, Work Orders, AMI Readings, Weather Data

Run after 03_generate_sample_data.sql
=============================================================================
*/

USE DATABASE RISK_PLANNING_DB;
USE SCHEMA ATOMIC;
USE WAREHOUSE RISK_COMPUTE_WH;

-- =====================
-- GENERATE RISK ASSESSMENTS
-- =====================
INSERT INTO RISK_ASSESSMENT (
    ASSESSMENT_ID, ASSET_ID, ASSESSMENT_DATE, FIRE_RISK_SCORE,
    IGNITION_PROBABILITY, CONSEQUENCE_SCORE, WIND_EXPOSURE_FACTOR,
    FUEL_LOAD_FACTOR, TERRAIN_FACTOR, ACCESS_DIFFICULTY_FACTOR,
    COMPOSITE_RISK_SCORE, RISK_TIER, ASSESSED_BY, ASSESSMENT_METHOD
)
SELECT
    'RSK-' || LPAD(ROW_NUMBER() OVER (ORDER BY a.ASSET_ID)::VARCHAR, 6, '0') AS ASSESSMENT_ID,
    a.ASSET_ID,
    DATEADD('day', -FLOOR(RANDOM() * 60), CURRENT_DATE()) AS ASSESSMENT_DATE,
    -- Fire risk based on fire threat district
    CASE c.FIRE_THREAT_DISTRICT
        WHEN 'TIER_3' THEN 0.7 + RANDOM() * 0.3
        WHEN 'TIER_2' THEN 0.5 + RANDOM() * 0.4
        WHEN 'TIER_1' THEN 0.3 + RANDOM() * 0.4
        ELSE 0.1 + RANDOM() * 0.3
    END AS FIRE_RISK_SCORE,
    -- Ignition probability based on asset condition and age
    LEAST(1.0, (1 - a.CONDITION_SCORE) * 0.5 + (a.ASSET_AGE_YEARS / 80) + RANDOM() * 0.2) AS IGNITION_PROBABILITY,
    -- Consequence based on customers
    LEAST(1.0, c.TOTAL_CUSTOMERS / 10000 + c.CRITICAL_FACILITIES / 50 + RANDOM() * 0.1) AS CONSEQUENCE_SCORE,
    -- Wind exposure
    CASE a.WIND_EXPOSURE
        WHEN 'HIGH' THEN 0.7 + RANDOM() * 0.3
        WHEN 'MEDIUM' THEN 0.4 + RANDOM() * 0.3
        ELSE 0.1 + RANDOM() * 0.3
    END AS WIND_EXPOSURE_FACTOR,
    -- Fuel load based on land use
    CASE l.LAND_USE
        WHEN 'WILDLAND' THEN 0.8 + RANDOM() * 0.2
        WHEN 'URBAN_INTERFACE' THEN 0.6 + RANDOM() * 0.3
        WHEN 'AGRICULTURAL' THEN 0.4 + RANDOM() * 0.3
        ELSE 0.2 + RANDOM() * 0.3
    END AS FUEL_LOAD_FACTOR,
    -- Terrain factor
    CASE l.TERRAIN_TYPE
        WHEN 'MOUNTAINOUS' THEN 0.7 + RANDOM() * 0.3
        WHEN 'CANYON' THEN 0.8 + RANDOM() * 0.2
        WHEN 'HILLY' THEN 0.5 + RANDOM() * 0.3
        ELSE 0.2 + RANDOM() * 0.3
    END AS TERRAIN_FACTOR,
    -- Access difficulty
    CASE 
        WHEN l.TERRAIN_TYPE IN ('MOUNTAINOUS', 'CANYON') THEN 0.7 + RANDOM() * 0.3
        WHEN l.LAND_USE = 'WILDLAND' THEN 0.6 + RANDOM() * 0.3
        ELSE 0.2 + RANDOM() * 0.4
    END AS ACCESS_DIFFICULTY_FACTOR,
    NULL AS COMPOSITE_RISK_SCORE,  -- Calculated below
    NULL AS RISK_TIER,  -- Calculated below
    'VIGIL_SYSTEM' AS ASSESSED_BY,
    'AUTOMATED' AS ASSESSMENT_METHOD
FROM ASSET a
JOIN CIRCUIT c ON a.CIRCUIT_ID = c.CIRCUIT_ID
JOIN LOCATION l ON a.LOCATION_ID = l.LOCATION_ID;

-- Calculate composite risk score
UPDATE RISK_ASSESSMENT
SET COMPOSITE_RISK_SCORE = ROUND(
    (FIRE_RISK_SCORE * 0.25 +
     IGNITION_PROBABILITY * 0.25 +
     CONSEQUENCE_SCORE * 0.20 +
     WIND_EXPOSURE_FACTOR * 0.10 +
     FUEL_LOAD_FACTOR * 0.10 +
     TERRAIN_FACTOR * 0.05 +
     ACCESS_DIFFICULTY_FACTOR * 0.05), 3);

-- Calculate risk tier
UPDATE RISK_ASSESSMENT
SET RISK_TIER = CASE
    WHEN COMPOSITE_RISK_SCORE >= 0.75 THEN 'CRITICAL'
    WHEN COMPOSITE_RISK_SCORE >= 0.55 THEN 'HIGH'
    WHEN COMPOSITE_RISK_SCORE >= 0.35 THEN 'MEDIUM'
    ELSE 'LOW'
END;

-- =====================
-- GENERATE WORK ORDERS
-- =====================
-- Vegetation management work orders
INSERT INTO WORK_ORDER (
    WORK_ORDER_ID, ASSET_ID, WORK_ORDER_TYPE, PRIORITY, STATUS,
    DESCRIPTION, ESTIMATED_COST, SCHEDULED_DATE, ASSIGNED_CREW, CREATED_BY
)
SELECT
    'WO-VEG-' || LPAD(ROW_NUMBER() OVER (ORDER BY v.ENCROACHMENT_ID)::VARCHAR, 6, '0') AS WORK_ORDER_ID,
    v.ASSET_ID,
    'VEGETATION_MANAGEMENT' AS WORK_ORDER_TYPE,
    v.TRIM_PRIORITY AS PRIORITY,
    CASE MOD(SEQ4(), 5)
        WHEN 0 THEN 'PENDING'
        WHEN 1 THEN 'SCHEDULED'
        WHEN 2 THEN 'IN_PROGRESS'
        WHEN 3 THEN 'COMPLETED'
        ELSE 'PENDING'
    END AS STATUS,
    'Trim ' || v.SPECIES || ' - Current clearance: ' || v.CURRENT_CLEARANCE_FT || 
    'ft, Required: ' || v.REQUIRED_CLEARANCE_FT || 'ft' AS DESCRIPTION,
    v.ESTIMATED_TRIM_COST AS ESTIMATED_COST,
    DATEADD('day', FLOOR(RANDOM() * 60), CURRENT_DATE()) AS SCHEDULED_DATE,
    'CREW-' || LPAD(MOD(SEQ4(), 20)::VARCHAR, 2, '0') AS ASSIGNED_CREW,
    'VIGIL_SYSTEM' AS CREATED_BY
FROM VEGETATION_ENCROACHMENT v
WHERE v.TRIM_PRIORITY IN ('CRITICAL', 'HIGH')
LIMIT 500;

-- Asset replacement work orders
INSERT INTO WORK_ORDER (
    WORK_ORDER_ID, ASSET_ID, WORK_ORDER_TYPE, PRIORITY, STATUS,
    DESCRIPTION, ESTIMATED_COST, SCHEDULED_DATE, ASSIGNED_CREW, CREATED_BY
)
SELECT
    'WO-REP-' || LPAD(ROW_NUMBER() OVER (ORDER BY a.ASSET_ID)::VARCHAR, 6, '0') AS WORK_ORDER_ID,
    a.ASSET_ID,
    'ASSET_REPLACEMENT' AS WORK_ORDER_TYPE,
    CASE 
        WHEN a.CONDITION_SCORE < 0.3 THEN 'CRITICAL'
        WHEN a.CONDITION_SCORE < 0.5 THEN 'HIGH'
        ELSE 'MEDIUM'
    END AS PRIORITY,
    CASE MOD(SEQ4(), 4)
        WHEN 0 THEN 'PENDING'
        WHEN 1 THEN 'SCHEDULED'
        WHEN 2 THEN 'IN_PROGRESS'
        ELSE 'PENDING'
    END AS STATUS,
    'Replace ' || a.ASSET_TYPE || ' (Age: ' || a.ASSET_AGE_YEARS || 'y, Condition: ' || 
    ROUND(a.CONDITION_SCORE * 100, 0) || '%)' AS DESCRIPTION,
    a.REPLACEMENT_COST AS ESTIMATED_COST,
    DATEADD('day', FLOOR(RANDOM() * 90), CURRENT_DATE()) AS SCHEDULED_DATE,
    'CREW-' || LPAD(MOD(SEQ4(), 20)::VARCHAR, 2, '0') AS ASSIGNED_CREW,
    'VIGIL_SYSTEM' AS CREATED_BY
FROM ASSET a
WHERE a.CONDITION_SCORE < 0.5
LIMIT 200;

-- Inspection work orders
INSERT INTO WORK_ORDER (
    WORK_ORDER_ID, ASSET_ID, WORK_ORDER_TYPE, PRIORITY, STATUS,
    DESCRIPTION, ESTIMATED_COST, SCHEDULED_DATE, ASSIGNED_CREW, CREATED_BY
)
SELECT
    'WO-INS-' || LPAD(ROW_NUMBER() OVER (ORDER BY a.ASSET_ID)::VARCHAR, 6, '0') AS WORK_ORDER_ID,
    a.ASSET_ID,
    'INSPECTION' AS WORK_ORDER_TYPE,
    'MEDIUM' AS PRIORITY,
    'SCHEDULED' AS STATUS,
    'Routine inspection of ' || a.ASSET_TYPE AS DESCRIPTION,
    200 + RANDOM() * 300 AS ESTIMATED_COST,
    a.NEXT_INSPECTION_DUE AS SCHEDULED_DATE,
    'CREW-' || LPAD(MOD(SEQ4(), 20)::VARCHAR, 2, '0') AS ASSIGNED_CREW,
    'VIGIL_SYSTEM' AS CREATED_BY
FROM ASSET a
WHERE a.NEXT_INSPECTION_DUE <= DATEADD('month', 3, CURRENT_DATE())
LIMIT 300;

-- =====================
-- GENERATE AMI READINGS (For Water Treeing Detection)
-- =====================
-- Focus on underground cables for Water Treeing
INSERT INTO AMI_READING (
    READING_ID, ASSET_ID, METER_ID, READING_TIMESTAMP,
    VOLTAGE_READING, VOLTAGE_DIP_FLAG, VOLTAGE_DIP_MAGNITUDE,
    CURRENT_READING, POWER_FACTOR, RAINFALL_24H_INCHES,
    RAIN_CORRELATED_DIP, TEMPERATURE_F, HUMIDITY_PCT
)
SELECT
    'AMI-' || LPAD(ROW_NUMBER() OVER (ORDER BY a.ASSET_ID, RANDOM())::VARCHAR, 8, '0') AS READING_ID,
    a.ASSET_ID,
    'MTR-' || LPAD(MOD(SEQ4(), 1000)::VARCHAR, 5, '0') AS METER_ID,
    DATEADD('hour', -SEQ4() * 4, CURRENT_TIMESTAMP()) AS READING_TIMESTAMP,
    -- Normal voltage ~120V, with some variation
    CASE 
        WHEN a.MATERIAL = 'XLPE' AND a.ASSET_AGE_YEARS > 15 AND a.MOISTURE_EXPOSURE = 'HIGH' 
             AND RANDOM() < 0.15 THEN 
            -- Water Treeing candidates have voltage dips
            120 - (3 + RANDOM() * 7)
        ELSE 
            120 + (RANDOM() - 0.5) * 4
    END AS VOLTAGE_READING,
    FALSE AS VOLTAGE_DIP_FLAG,  -- Set below
    NULL AS VOLTAGE_DIP_MAGNITUDE,  -- Set below
    95 + RANDOM() * 10 AS CURRENT_READING,
    0.85 + RANDOM() * 0.15 AS POWER_FACTOR,
    -- Rainfall - more in PNW and NorCal
    CASE 
        WHEN l.REGION IN ('PNW', 'NorCal') THEN RANDOM() * 2
        WHEN l.REGION = 'Mountain' THEN RANDOM() * 1
        ELSE RANDOM() * 0.5
    END AS RAINFALL_24H_INCHES,
    FALSE AS RAIN_CORRELATED_DIP,  -- Set below
    50 + RANDOM() * 50 AS TEMPERATURE_F,
    30 + RANDOM() * 60 AS HUMIDITY_PCT
FROM ASSET a
JOIN LOCATION l ON a.LOCATION_ID = l.LOCATION_ID
CROSS JOIN TABLE(GENERATOR(ROWCOUNT => 50)) g
WHERE a.ASSET_TYPE = 'UNDERGROUND_CABLE'
LIMIT 50000;

-- Flag voltage dips
UPDATE AMI_READING
SET VOLTAGE_DIP_FLAG = TRUE,
    VOLTAGE_DIP_MAGNITUDE = 120 - VOLTAGE_READING
WHERE VOLTAGE_READING < 117;

-- Flag rain-correlated dips (key for Water Treeing detection)
UPDATE AMI_READING
SET RAIN_CORRELATED_DIP = TRUE
WHERE VOLTAGE_DIP_FLAG = TRUE 
AND RAINFALL_24H_INCHES > 0.1;

-- =====================
-- GENERATE WEATHER DATA
-- =====================
INSERT INTO WEATHER_DATA (
    WEATHER_ID, LOCATION_ID, OBSERVATION_TIMESTAMP,
    TEMPERATURE_F, HUMIDITY_PCT, WIND_SPEED_MPH, WIND_GUST_MPH,
    WIND_DIRECTION, PRECIPITATION_INCHES, FIRE_WEATHER_INDEX, RED_FLAG_WARNING
)
SELECT
    'WX-' || LPAD(ROW_NUMBER() OVER (ORDER BY l.LOCATION_ID, RANDOM())::VARCHAR, 8, '0') AS WEATHER_ID,
    l.LOCATION_ID,
    DATEADD('hour', -SEQ4() * 6, CURRENT_TIMESTAMP()) AS OBSERVATION_TIMESTAMP,
    CASE l.REGION
        WHEN 'Southwest' THEN 70 + RANDOM() * 40
        WHEN 'Mountain' THEN 30 + RANDOM() * 50
        WHEN 'PNW' THEN 40 + RANDOM() * 40
        ELSE 50 + RANDOM() * 40
    END AS TEMPERATURE_F,
    CASE l.REGION
        WHEN 'Southwest' THEN 10 + RANDOM() * 30
        WHEN 'PNW' THEN 50 + RANDOM() * 40
        ELSE 30 + RANDOM() * 50
    END AS HUMIDITY_PCT,
    5 + RANDOM() * 25 AS WIND_SPEED_MPH,
    CASE WHEN RANDOM() < 0.2 THEN 30 + RANDOM() * 50 ELSE NULL END AS WIND_GUST_MPH,
    CASE MOD(SEQ4(), 8)
        WHEN 0 THEN 'N'
        WHEN 1 THEN 'NE'
        WHEN 2 THEN 'E'
        WHEN 3 THEN 'SE'
        WHEN 4 THEN 'S'
        WHEN 5 THEN 'SW'
        WHEN 6 THEN 'W'
        ELSE 'NW'
    END AS WIND_DIRECTION,
    CASE WHEN RANDOM() < 0.3 THEN RANDOM() * 0.5 ELSE 0 END AS PRECIPITATION_INCHES,
    RANDOM() * 100 AS FIRE_WEATHER_INDEX,
    FALSE AS RED_FLAG_WARNING  -- Set below
FROM LOCATION l
CROSS JOIN TABLE(GENERATOR(ROWCOUNT => 20)) g
LIMIT 10000;

-- Set red flag warnings for high fire weather
UPDATE WEATHER_DATA
SET RED_FLAG_WARNING = TRUE
WHERE FIRE_WEATHER_INDEX > 80 
AND HUMIDITY_PCT < 20 
AND WIND_SPEED_MPH > 20;

-- =====================
-- POPULATE ML PREDICTIONS
-- =====================
USE SCHEMA ML;

-- Asset Health Predictions
INSERT INTO ASSET_HEALTH_PREDICTION (
    PREDICTION_ID, ASSET_ID, PREDICTION_DATE,
    PREDICTED_HEALTH_SCORE, CONFIDENCE_INTERVAL_LOW, CONFIDENCE_INTERVAL_HIGH,
    DAYS_TO_CRITICAL, MODEL_VERSION
)
SELECT
    'AHP-' || LPAD(ROW_NUMBER() OVER (ORDER BY a.ASSET_ID)::VARCHAR, 6, '0') AS PREDICTION_ID,
    a.ASSET_ID,
    CURRENT_DATE() AS PREDICTION_DATE,
    GREATEST(0.1, a.CONDITION_SCORE - (a.ASSET_AGE_YEARS / 200) + (RANDOM() - 0.5) * 0.1) AS PREDICTED_HEALTH_SCORE,
    GREATEST(0.05, a.CONDITION_SCORE - 0.1) AS CONFIDENCE_INTERVAL_LOW,
    LEAST(1.0, a.CONDITION_SCORE + 0.1) AS CONFIDENCE_INTERVAL_HIGH,
    CASE 
        WHEN a.CONDITION_SCORE < 0.3 THEN FLOOR(RANDOM() * 180)
        WHEN a.CONDITION_SCORE < 0.5 THEN FLOOR(180 + RANDOM() * 365)
        WHEN a.CONDITION_SCORE < 0.7 THEN FLOOR(365 + RANDOM() * 730)
        ELSE FLOOR(730 + RANDOM() * 1825)
    END AS DAYS_TO_CRITICAL,
    'v1.0.0' AS MODEL_VERSION
FROM RISK_PLANNING_DB.ATOMIC.ASSET a;

-- Cable Failure Predictions (Water Treeing)
INSERT INTO CABLE_FAILURE_PREDICTION (
    PREDICTION_ID, ASSET_ID, PREDICTION_DATE,
    CABLE_AGE_YEARS, MATERIAL, MOISTURE_EXPOSURE,
    VOLTAGE_DIP_COUNT, RAIN_CORRELATION_SCORE, FAILURE_PROBABILITY,
    RISK_TIER, CUSTOMER_IMPACT_COUNT, ESTIMATED_REPLACEMENT_COST, MODEL_VERSION
)
SELECT
    'CFP-' || LPAD(ROW_NUMBER() OVER (ORDER BY a.ASSET_ID)::VARCHAR, 6, '0') AS PREDICTION_ID,
    a.ASSET_ID,
    CURRENT_DATE() AS PREDICTION_DATE,
    a.ASSET_AGE_YEARS,
    a.MATERIAL,
    a.MOISTURE_EXPOSURE,
    -- Count voltage dips
    COALESCE(ami.DIP_COUNT, 0) AS VOLTAGE_DIP_COUNT,
    -- Rain correlation score (key for Water Treeing)
    CASE 
        WHEN a.MATERIAL = 'XLPE' AND a.ASSET_AGE_YEARS BETWEEN 15 AND 25 AND a.MOISTURE_EXPOSURE = 'HIGH' THEN
            0.5 + RANDOM() * 0.4  -- High correlation for Water Treeing candidates
        WHEN a.MATERIAL = 'XLPE' AND a.ASSET_AGE_YEARS > 10 THEN
            0.2 + RANDOM() * 0.4
        ELSE
            RANDOM() * 0.3
    END AS RAIN_CORRELATION_SCORE,
    -- Failure probability
    CASE 
        WHEN a.MATERIAL = 'XLPE' AND a.ASSET_AGE_YEARS BETWEEN 15 AND 25 AND a.MOISTURE_EXPOSURE = 'HIGH' THEN
            0.6 + RANDOM() * 0.35  -- High failure probability
        WHEN a.MATERIAL = 'XLPE' AND a.ASSET_AGE_YEARS > 20 THEN
            0.3 + RANDOM() * 0.4
        ELSE
            RANDOM() * 0.3
    END AS FAILURE_PROBABILITY,
    NULL AS RISK_TIER,  -- Set below
    c.TOTAL_CUSTOMERS AS CUSTOMER_IMPACT_COUNT,
    a.REPLACEMENT_COST AS ESTIMATED_REPLACEMENT_COST,
    'v1.0.0' AS MODEL_VERSION
FROM RISK_PLANNING_DB.ATOMIC.ASSET a
JOIN RISK_PLANNING_DB.ATOMIC.CIRCUIT c ON a.CIRCUIT_ID = c.CIRCUIT_ID
LEFT JOIN (
    SELECT ASSET_ID, COUNT(*) AS DIP_COUNT
    FROM RISK_PLANNING_DB.ATOMIC.AMI_READING
    WHERE VOLTAGE_DIP_FLAG = TRUE
    GROUP BY ASSET_ID
) ami ON a.ASSET_ID = ami.ASSET_ID
WHERE a.ASSET_TYPE = 'UNDERGROUND_CABLE';

-- Set risk tier for cable predictions
UPDATE CABLE_FAILURE_PREDICTION
SET RISK_TIER = CASE
    WHEN FAILURE_PROBABILITY >= 0.75 THEN 'CRITICAL'
    WHEN FAILURE_PROBABILITY >= 0.55 THEN 'HIGH'
    WHEN FAILURE_PROBABILITY >= 0.35 THEN 'MEDIUM'
    ELSE 'LOW'
END;

SELECT 'Sample data generation complete - Part 2!' AS STATUS;
