-- ============================================================================
-- VIGIL Risk-Based Planning Intelligence Platform
-- CONSTRUCTION_RISK Schema - Data Mart Views for Analytics
-- ============================================================================

USE DATABASE RISK_PLANNING_DB;
USE SCHEMA CONSTRUCTION_RISK;

-- ============================================================================
-- CIRCUIT_RISK_PROFILE - Aggregated risk metrics per circuit
-- ============================================================================
CREATE OR REPLACE VIEW CIRCUIT_RISK_PROFILE AS
SELECT 
    c.CIRCUIT_ID,
    c.CIRCUIT_NAME,
    c.SUBSTATION_NAME,
    c.DISTRICT,
    c.VOLTAGE_CLASS,
    c.FIRE_THREAT_TIER,
    c.TOTAL_MILES,
    c.OVERHEAD_MILES,
    c.UNDERGROUND_MILES,
    c.CUSTOMER_COUNT,
    
    -- Location Info
    l.ZONE_NAME,
    l.REGION,
    l.STATE,
    l.HFTD_FLAG,
    
    -- Asset Counts
    COUNT(DISTINCT a.ASSET_ID) AS TOTAL_ASSETS,
    SUM(CASE WHEN a.ASSET_TYPE = 'POLE' THEN 1 ELSE 0 END) AS POLE_COUNT,
    SUM(CASE WHEN a.ASSET_TYPE = 'CONDUCTOR' THEN 1 ELSE 0 END) AS CONDUCTOR_SPANS,
    SUM(CASE WHEN a.ASSET_TYPE = 'TRANSFORMER' THEN 1 ELSE 0 END) AS TRANSFORMER_COUNT,
    SUM(CASE WHEN a.ASSET_TYPE = 'CABLE_UNDERGROUND' THEN 1 ELSE 0 END) AS UG_CABLE_SEGMENTS,
    
    -- Risk Metrics
    ROUND(AVG(a.COMPOSITE_RISK_SCORE), 2) AS AVG_RISK_SCORE,
    MAX(a.COMPOSITE_RISK_SCORE) AS MAX_RISK_SCORE,
    SUM(CASE WHEN a.COMPOSITE_RISK_SCORE >= 80 THEN 1 ELSE 0 END) AS CRITICAL_RISK_ASSETS,
    SUM(CASE WHEN a.COMPOSITE_RISK_SCORE >= 60 AND a.COMPOSITE_RISK_SCORE < 80 THEN 1 ELSE 0 END) AS HIGH_RISK_ASSETS,
    SUM(CASE WHEN a.COMPOSITE_RISK_SCORE >= 40 AND a.COMPOSITE_RISK_SCORE < 60 THEN 1 ELSE 0 END) AS MEDIUM_RISK_ASSETS,
    SUM(CASE WHEN a.COMPOSITE_RISK_SCORE < 40 THEN 1 ELSE 0 END) AS LOW_RISK_ASSETS,
    
    -- Vegetation Metrics
    COUNT(DISTINCT ve.ENCROACHMENT_ID) AS VEG_ENCROACHMENT_COUNT,
    SUM(CASE WHEN ve.CLEARANCE_STATUS = 'VIOLATION' THEN 1 ELSE 0 END) AS SPANS_IN_VIOLATION,
    SUM(CASE WHEN ve.CLEARANCE_STATUS = 'CRITICAL' THEN 1 ELSE 0 END) AS SPANS_CRITICAL,
    SUM(CASE WHEN ve.CLEARANCE_STATUS = 'MARGINAL' THEN 1 ELSE 0 END) AS SPANS_MARGINAL,
    ROUND(AVG(ve.DISTANCE_TO_CONDUCTOR_FT), 2) AS AVG_CLEARANCE_FT,
    MIN(ve.DISTANCE_TO_CONDUCTOR_FT) AS MIN_CLEARANCE_FT,
    
    -- Trim Status
    c.LAST_TRIM_DATE,
    c.NEXT_SCHEDULED_TRIM,
    DATEDIFF('day', CURRENT_DATE(), c.NEXT_SCHEDULED_TRIM) AS DAYS_TO_SCHEDULED_TRIM,
    
    -- Reliability
    c.SAIDI_MINUTES,
    c.SAIFI_COUNT

FROM ATOMIC.CIRCUIT c
LEFT JOIN ATOMIC.LOCATION l ON c.LOCATION_ID = l.LOCATION_ID
LEFT JOIN ATOMIC.ASSET a ON c.CIRCUIT_ID = a.CIRCUIT_ID AND a.STATUS = 'IN_SERVICE'
LEFT JOIN ATOMIC.VEGETATION_ENCROACHMENT ve ON a.ASSET_ID = ve.ASSET_ID
GROUP BY 
    c.CIRCUIT_ID, c.CIRCUIT_NAME, c.SUBSTATION_NAME, c.DISTRICT, c.VOLTAGE_CLASS,
    c.FIRE_THREAT_TIER, c.TOTAL_MILES, c.OVERHEAD_MILES, c.UNDERGROUND_MILES,
    c.CUSTOMER_COUNT, l.ZONE_NAME, l.REGION, l.STATE, l.HFTD_FLAG,
    c.LAST_TRIM_DATE, c.NEXT_SCHEDULED_TRIM, c.SAIDI_MINUTES, c.SAIFI_COUNT;

COMMENT ON VIEW CIRCUIT_RISK_PROFILE IS 'Aggregated risk and vegetation metrics per circuit for dashboard views';

-- ============================================================================
-- ASSET_HEALTH_DASHBOARD - Asset-level view with all risk factors
-- ============================================================================
CREATE OR REPLACE VIEW ASSET_HEALTH_DASHBOARD AS
SELECT 
    a.ASSET_ID,
    a.ASSET_NAME,
    a.ASSET_TYPE,
    a.ASSET_SUBTYPE,
    
    -- Location
    a.LATITUDE,
    a.LONGITUDE,
    c.CIRCUIT_NAME,
    c.DISTRICT,
    l.ZONE_NAME,
    l.REGION,
    l.FIRE_THREAT_TIER,
    l.HFTD_FLAG,
    
    -- Asset Details
    a.MANUFACTURER,
    a.INSTALL_DATE,
    a.AGE_YEARS,
    a.EXPECTED_LIFE_YEARS,
    a.VOLTAGE_CLASS,
    a.CONDITION_SCORE,
    a.LAST_INSPECTION_DATE,
    
    -- Risk Scores
    a.COMPOSITE_RISK_SCORE,
    a.FAILURE_PROBABILITY,
    a.IGNITION_RISK_SCORE,
    CASE 
        WHEN a.COMPOSITE_RISK_SCORE >= 80 THEN 'CRITICAL'
        WHEN a.COMPOSITE_RISK_SCORE >= 60 THEN 'HIGH'
        WHEN a.COMPOSITE_RISK_SCORE >= 40 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS RISK_TIER,
    
    -- Vegetation (if applicable)
    ve.DISTANCE_TO_CONDUCTOR_FT,
    ve.TREE_SPECIES,
    ve.GROWTH_RATE_CATEGORY,
    ve.CLEARANCE_STATUS,
    ve.DAYS_TO_CRITICAL AS VEG_DAYS_TO_CRITICAL,
    
    -- Underground Cable Specific (for Hidden Discovery)
    a.INSULATION_TYPE,
    a.MOISTURE_EXPOSURE,
    cfp.WATER_TREEING_PROBABILITY,
    cfp.WATER_TREEING_SEVERITY,
    cfp.RAIN_CORRELATION_SCORE,
    
    -- Latest Risk Assessment
    ra.RECOMMENDED_ACTION,
    ra.RECOMMENDED_PRIORITY,
    ra.ESTIMATED_RISK_REDUCTION,
    
    -- Status
    a.STATUS,
    a.REPLACEMENT_PRIORITY

FROM ATOMIC.ASSET a
LEFT JOIN ATOMIC.CIRCUIT c ON a.CIRCUIT_ID = c.CIRCUIT_ID
LEFT JOIN ATOMIC.LOCATION l ON a.LOCATION_ID = l.LOCATION_ID
LEFT JOIN ATOMIC.VEGETATION_ENCROACHMENT ve ON a.ASSET_ID = ve.ASSET_ID
LEFT JOIN ML.CABLE_FAILURE_PREDICTION cfp ON a.ASSET_ID = cfp.ASSET_ID 
    AND cfp.PREDICTION_DATE = (SELECT MAX(PREDICTION_DATE) FROM ML.CABLE_FAILURE_PREDICTION WHERE ASSET_ID = a.ASSET_ID)
LEFT JOIN ATOMIC.RISK_ASSESSMENT ra ON a.ASSET_ID = ra.ASSET_ID
    AND ra.ASSESSMENT_DATE = (SELECT MAX(ASSESSMENT_DATE) FROM ATOMIC.RISK_ASSESSMENT WHERE ASSET_ID = a.ASSET_ID)
WHERE a.STATUS = 'IN_SERVICE';

COMMENT ON VIEW ASSET_HEALTH_DASHBOARD IS 'Comprehensive asset health view with risk scores and vegetation data';

-- ============================================================================
-- OPTIMIZED_WORK_PLAN - Prioritized work recommendations
-- ============================================================================
CREATE OR REPLACE VIEW OPTIMIZED_WORK_PLAN AS
WITH RankedActions AS (
    SELECT 
        a.ASSET_ID,
        a.ASSET_NAME,
        a.ASSET_TYPE,
        c.CIRCUIT_ID,
        c.CIRCUIT_NAME,
        c.DISTRICT,
        l.ZONE_NAME,
        l.FIRE_THREAT_TIER,
        
        -- Risk Info
        a.COMPOSITE_RISK_SCORE,
        a.IGNITION_RISK_SCORE,
        
        -- Determine Action Type
        CASE 
            WHEN ve.CLEARANCE_STATUS IN ('VIOLATION', 'CRITICAL') THEN 'TRIM'
            WHEN cfp.WATER_TREEING_SEVERITY IN ('MODERATE', 'SEVERE') THEN 'REPLACE'
            WHEN a.CONDITION_SCORE <= 2 THEN 'REPLACE'
            WHEN a.COMPOSITE_RISK_SCORE >= 60 THEN 'INSPECT'
            ELSE 'MONITOR'
        END AS RECOMMENDED_ACTION,
        
        -- Priority Calculation
        CASE 
            WHEN l.FIRE_THREAT_TIER = 'TIER_3' AND a.COMPOSITE_RISK_SCORE >= 80 THEN 1
            WHEN l.FIRE_THREAT_TIER = 'TIER_3' AND ve.CLEARANCE_STATUS = 'VIOLATION' THEN 1
            WHEN cfp.WATER_TREEING_SEVERITY = 'SEVERE' THEN 1
            WHEN l.FIRE_THREAT_TIER = 'TIER_2' AND a.COMPOSITE_RISK_SCORE >= 80 THEN 2
            WHEN ve.CLEARANCE_STATUS = 'CRITICAL' THEN 2
            WHEN cfp.WATER_TREEING_SEVERITY = 'MODERATE' THEN 2
            WHEN a.COMPOSITE_RISK_SCORE >= 60 THEN 3
            WHEN ve.CLEARANCE_STATUS = 'MARGINAL' THEN 3
            ELSE 4
        END AS PRIORITY_RANK,
        
        -- Vegetation Details
        ve.DISTANCE_TO_CONDUCTOR_FT,
        ve.TREE_SPECIES,
        ve.DAYS_TO_CRITICAL AS VEG_DAYS_TO_CRITICAL,
        
        -- Cable Details
        cfp.WATER_TREEING_PROBABILITY,
        cfp.PROACTIVE_REPLACEMENT_COST,
        cfp.EMERGENCY_REPAIR_COST,
        
        -- Cost-Benefit
        COALESCE(ra.ESTIMATED_RISK_REDUCTION, 0) AS ESTIMATED_RISK_REDUCTION,
        
        -- Location for routing
        a.LATITUDE,
        a.LONGITUDE

    FROM ATOMIC.ASSET a
    LEFT JOIN ATOMIC.CIRCUIT c ON a.CIRCUIT_ID = c.CIRCUIT_ID
    LEFT JOIN ATOMIC.LOCATION l ON a.LOCATION_ID = l.LOCATION_ID
    LEFT JOIN ATOMIC.VEGETATION_ENCROACHMENT ve ON a.ASSET_ID = ve.ASSET_ID
    LEFT JOIN ML.CABLE_FAILURE_PREDICTION cfp ON a.ASSET_ID = cfp.ASSET_ID
    LEFT JOIN ATOMIC.RISK_ASSESSMENT ra ON a.ASSET_ID = ra.ASSET_ID
    WHERE a.STATUS = 'IN_SERVICE'
      AND (
          ve.CLEARANCE_STATUS IN ('VIOLATION', 'CRITICAL', 'MARGINAL')
          OR cfp.WATER_TREEING_SEVERITY IN ('MODERATE', 'SEVERE')
          OR a.COMPOSITE_RISK_SCORE >= 60
          OR a.CONDITION_SCORE <= 2
      )
)
SELECT 
    *,
    CASE PRIORITY_RANK
        WHEN 1 THEN 'EMERGENCY'
        WHEN 2 THEN 'URGENT'
        WHEN 3 THEN 'HIGH'
        ELSE 'MEDIUM'
    END AS PRIORITY_LABEL,
    ROW_NUMBER() OVER (ORDER BY PRIORITY_RANK, COMPOSITE_RISK_SCORE DESC) AS WORK_SEQUENCE
FROM RankedActions;

COMMENT ON VIEW OPTIMIZED_WORK_PLAN IS 'Prioritized work plan based on risk scores and fire threat';

-- ============================================================================
-- FIRE_SEASON_READINESS - Dashboard metrics for fire season prep
-- ============================================================================
CREATE OR REPLACE VIEW FIRE_SEASON_READINESS AS
WITH FireSeasonDates AS (
    -- Dynamic fire season calculation based on region
    SELECT 
        REGION,
        CASE REGION
            WHEN 'NORCAL' THEN DATE_FROM_PARTS(YEAR(CURRENT_DATE()), 5, 15)
            WHEN 'SOCAL' THEN DATE_FROM_PARTS(YEAR(CURRENT_DATE()), 5, 1)
            WHEN 'SOUTHWEST' THEN DATE_FROM_PARTS(YEAR(CURRENT_DATE()), 6, 1)
            WHEN 'MOUNTAIN' THEN DATE_FROM_PARTS(YEAR(CURRENT_DATE()), 6, 15)
            WHEN 'PNW' THEN DATE_FROM_PARTS(YEAR(CURRENT_DATE()), 7, 1)
            ELSE DATE_FROM_PARTS(YEAR(CURRENT_DATE()), 6, 1)
        END AS FIRE_SEASON_START,
        CASE REGION
            WHEN 'NORCAL' THEN DATE_FROM_PARTS(YEAR(CURRENT_DATE()), 11, 15)
            WHEN 'SOCAL' THEN DATE_FROM_PARTS(YEAR(CURRENT_DATE()), 12, 15)
            WHEN 'SOUTHWEST' THEN DATE_FROM_PARTS(YEAR(CURRENT_DATE()), 9, 30)
            WHEN 'MOUNTAIN' THEN DATE_FROM_PARTS(YEAR(CURRENT_DATE()), 10, 15)
            WHEN 'PNW' THEN DATE_FROM_PARTS(YEAR(CURRENT_DATE()), 10, 1)
            ELSE DATE_FROM_PARTS(YEAR(CURRENT_DATE()), 11, 1)
        END AS FIRE_SEASON_END
    FROM (SELECT DISTINCT REGION FROM ATOMIC.LOCATION)
),
RegionMetrics AS (
    SELECT 
        l.REGION,
        COUNT(DISTINCT a.ASSET_ID) AS TOTAL_ASSETS,
        SUM(CASE WHEN a.COMPOSITE_RISK_SCORE >= 60 THEN 1 ELSE 0 END) AS HIGH_RISK_ASSETS,
        SUM(CASE WHEN ve.CLEARANCE_STATUS IN ('VIOLATION', 'CRITICAL') THEN 1 ELSE 0 END) AS SPANS_NEEDING_TRIM,
        SUM(CASE WHEN ve.CLEARANCE_STATUS = 'COMPLIANT' THEN 1 ELSE 0 END) AS SPANS_COMPLIANT,
        COUNT(DISTINCT wo.WORK_ORDER_ID) AS OPEN_WORK_ORDERS,
        SUM(CASE WHEN wo.STATUS = 'COMPLETED' AND wo.COMPLETION_DATE >= DATE_TRUNC('YEAR', CURRENT_DATE()) THEN 1 ELSE 0 END) AS COMPLETED_YTD
    FROM ATOMIC.LOCATION l
    LEFT JOIN ATOMIC.ASSET a ON l.LOCATION_ID = a.LOCATION_ID AND a.STATUS = 'IN_SERVICE'
    LEFT JOIN ATOMIC.VEGETATION_ENCROACHMENT ve ON a.ASSET_ID = ve.ASSET_ID
    LEFT JOIN ATOMIC.WORK_ORDER wo ON a.ASSET_ID = wo.ASSET_ID AND wo.STATUS NOT IN ('COMPLETED', 'CANCELLED')
    GROUP BY l.REGION
)
SELECT 
    rm.REGION,
    fsd.FIRE_SEASON_START,
    fsd.FIRE_SEASON_END,
    DATEDIFF('day', CURRENT_DATE(), fsd.FIRE_SEASON_START) AS DAYS_TO_FIRE_SEASON,
    CASE 
        WHEN CURRENT_DATE() BETWEEN fsd.FIRE_SEASON_START AND fsd.FIRE_SEASON_END THEN TRUE 
        ELSE FALSE 
    END AS IN_FIRE_SEASON,
    
    -- Asset Metrics
    rm.TOTAL_ASSETS,
    rm.HIGH_RISK_ASSETS,
    ROUND(100.0 * rm.HIGH_RISK_ASSETS / NULLIF(rm.TOTAL_ASSETS, 0), 1) AS HIGH_RISK_PCT,
    
    -- Vegetation Metrics
    rm.SPANS_NEEDING_TRIM,
    rm.SPANS_COMPLIANT,
    ROUND(100.0 * rm.SPANS_COMPLIANT / NULLIF(rm.SPANS_NEEDING_TRIM + rm.SPANS_COMPLIANT, 0), 1) AS VEG_COMPLIANCE_PCT,
    
    -- Work Order Metrics
    rm.OPEN_WORK_ORDERS,
    rm.COMPLETED_YTD,
    
    -- Readiness Score (simplified)
    ROUND(
        100 - (
            (100.0 * rm.HIGH_RISK_ASSETS / NULLIF(rm.TOTAL_ASSETS, 0)) * 0.4 +
            (100.0 * rm.SPANS_NEEDING_TRIM / NULLIF(rm.SPANS_NEEDING_TRIM + rm.SPANS_COMPLIANT, 0)) * 0.6
        ), 1
    ) AS READINESS_SCORE

FROM RegionMetrics rm
JOIN FireSeasonDates fsd ON rm.REGION = fsd.REGION;

COMMENT ON VIEW FIRE_SEASON_READINESS IS 'Fire season readiness metrics by region with dynamic date calculation';

-- ============================================================================
-- WATER_TREEING_ANALYSIS - Hidden Discovery analysis view
-- ============================================================================
CREATE OR REPLACE VIEW WATER_TREEING_ANALYSIS AS
SELECT 
    a.ASSET_ID,
    a.ASSET_NAME,
    c.CIRCUIT_NAME,
    c.DISTRICT,
    l.REGION,
    
    -- Asset Details
    a.INSTALL_DATE,
    a.AGE_YEARS,
    a.INSULATION_TYPE,
    a.MOISTURE_EXPOSURE,
    a.SOIL_TYPE,
    
    -- AMI Anomaly Metrics
    COUNT(DISTINCT amr.READING_ID) AS TOTAL_READINGS,
    SUM(CASE WHEN amr.VOLTAGE_DIP_FLAG THEN 1 ELSE 0 END) AS VOLTAGE_DIP_COUNT,
    SUM(CASE WHEN amr.RAIN_CORRELATED_DIP THEN 1 ELSE 0 END) AS RAIN_CORRELATED_DIP_COUNT,
    AVG(CASE WHEN amr.VOLTAGE_DIP_FLAG THEN amr.VOLTAGE_DIP_PCT ELSE NULL END) AS AVG_DIP_MAGNITUDE_PCT,
    
    -- Correlation Analysis
    ROUND(
        100.0 * SUM(CASE WHEN amr.RAIN_CORRELATED_DIP THEN 1 ELSE 0 END) / 
        NULLIF(SUM(CASE WHEN amr.RAINFALL_MM > 10 THEN 1 ELSE 0 END), 0), 
    2) AS RAIN_DIP_CORRELATION_PCT,
    
    -- ML Predictions
    cfp.WATER_TREEING_PROBABILITY,
    cfp.WATER_TREEING_SEVERITY,
    cfp.FAILURE_PROBABILITY_30D,
    cfp.FAILURE_PROBABILITY_90D,
    cfp.RECOMMENDED_ACTION,
    
    -- Cost Analysis
    cfp.PROACTIVE_REPLACEMENT_COST,
    cfp.EMERGENCY_REPAIR_COST,
    cfp.EMERGENCY_REPAIR_COST - cfp.PROACTIVE_REPLACEMENT_COST AS POTENTIAL_SAVINGS,
    
    -- Risk Flag
    CASE 
        WHEN cfp.WATER_TREEING_SEVERITY = 'SEVERE' THEN 'CRITICAL'
        WHEN cfp.WATER_TREEING_SEVERITY = 'MODERATE' THEN 'HIGH'
        WHEN cfp.WATER_TREEING_SEVERITY = 'EARLY' THEN 'MEDIUM'
        ELSE 'LOW'
    END AS RISK_LEVEL,
    
    -- Location
    a.LATITUDE,
    a.LONGITUDE

FROM ATOMIC.ASSET a
LEFT JOIN ATOMIC.CIRCUIT c ON a.CIRCUIT_ID = c.CIRCUIT_ID
LEFT JOIN ATOMIC.LOCATION l ON a.LOCATION_ID = l.LOCATION_ID
LEFT JOIN ATOMIC.AMI_READING amr ON a.ASSET_ID = amr.ASSET_ID
LEFT JOIN ML.CABLE_FAILURE_PREDICTION cfp ON a.ASSET_ID = cfp.ASSET_ID
WHERE a.ASSET_TYPE = 'CABLE_UNDERGROUND'
  AND a.STATUS = 'IN_SERVICE'
GROUP BY 
    a.ASSET_ID, a.ASSET_NAME, c.CIRCUIT_NAME, c.DISTRICT, l.REGION,
    a.INSTALL_DATE, a.AGE_YEARS, a.INSULATION_TYPE, a.MOISTURE_EXPOSURE, a.SOIL_TYPE,
    cfp.WATER_TREEING_PROBABILITY, cfp.WATER_TREEING_SEVERITY, 
    cfp.FAILURE_PROBABILITY_30D, cfp.FAILURE_PROBABILITY_90D, cfp.RECOMMENDED_ACTION,
    cfp.PROACTIVE_REPLACEMENT_COST, cfp.EMERGENCY_REPAIR_COST,
    a.LATITUDE, a.LONGITUDE;

COMMENT ON VIEW WATER_TREEING_ANALYSIS IS 'Hidden Discovery view: Underground cable analysis for Water Treeing detection';

-- ============================================================================
-- VEGETATION_TRIM_PRIORITIES - Prioritized vegetation trimming list
-- ============================================================================
CREATE OR REPLACE VIEW VEGETATION_TRIM_PRIORITIES AS
SELECT 
    ve.ENCROACHMENT_ID,
    a.ASSET_ID,
    a.ASSET_NAME,
    c.CIRCUIT_ID,
    c.CIRCUIT_NAME,
    c.DISTRICT,
    l.ZONE_NAME,
    l.FIRE_THREAT_TIER,
    
    -- Vegetation Details
    ve.TREE_SPECIES,
    ve.TREE_HEIGHT_FT,
    ve.TREE_HEALTH,
    ve.DISTANCE_TO_CONDUCTOR_FT,
    ve.REQUIRED_CLEARANCE_FT,
    ve.CLEARANCE_STATUS,
    ve.GROWTH_RATE_CATEGORY,
    ve.GROWTH_RATE_ANNUAL_FT,
    
    -- Predictions
    ve.PREDICTED_ENCROACHMENT_30D_FT,
    ve.PREDICTED_ENCROACHMENT_90D_FT,
    ve.DAYS_TO_CRITICAL,
    
    -- Risk Factors
    ve.STRIKE_POTENTIAL,
    ve.FALL_IN_POTENTIAL,
    ve.BLOW_IN_POTENTIAL,
    
    -- Priority Calculation
    CASE 
        WHEN ve.CLEARANCE_STATUS = 'VIOLATION' AND l.FIRE_THREAT_TIER = 'TIER_3' THEN 1
        WHEN ve.CLEARANCE_STATUS = 'CRITICAL' AND l.FIRE_THREAT_TIER = 'TIER_3' THEN 1
        WHEN ve.CLEARANCE_STATUS = 'VIOLATION' THEN 2
        WHEN ve.CLEARANCE_STATUS = 'CRITICAL' THEN 2
        WHEN ve.DAYS_TO_CRITICAL <= 30 AND l.HFTD_FLAG THEN 2
        WHEN ve.CLEARANCE_STATUS = 'MARGINAL' AND l.FIRE_THREAT_TIER IN ('TIER_2', 'TIER_3') THEN 3
        WHEN ve.DAYS_TO_CRITICAL <= 60 THEN 3
        ELSE 4
    END AS TRIM_PRIORITY,
    
    -- Urgency Label
    CASE 
        WHEN ve.CLEARANCE_STATUS IN ('VIOLATION', 'CRITICAL') AND l.FIRE_THREAT_TIER = 'TIER_3' THEN 'IMMEDIATE'
        WHEN ve.CLEARANCE_STATUS IN ('VIOLATION', 'CRITICAL') THEN 'URGENT'
        WHEN ve.DAYS_TO_CRITICAL <= 30 THEN 'HIGH'
        WHEN ve.DAYS_TO_CRITICAL <= 60 THEN 'MEDIUM'
        ELSE 'ROUTINE'
    END AS URGENCY,
    
    -- Location for routing
    a.LATITUDE,
    a.LONGITUDE,
    
    -- Existing Work Order Check
    CASE WHEN wo.WORK_ORDER_ID IS NOT NULL THEN TRUE ELSE FALSE END AS HAS_WORK_ORDER,
    wo.WORK_ORDER_NUMBER,
    wo.STATUS AS WORK_ORDER_STATUS

FROM ATOMIC.VEGETATION_ENCROACHMENT ve
JOIN ATOMIC.ASSET a ON ve.ASSET_ID = a.ASSET_ID
JOIN ATOMIC.CIRCUIT c ON a.CIRCUIT_ID = c.CIRCUIT_ID
JOIN ATOMIC.LOCATION l ON a.LOCATION_ID = l.LOCATION_ID
LEFT JOIN ATOMIC.WORK_ORDER wo ON a.ASSET_ID = wo.ASSET_ID 
    AND wo.ACTIVITY_TYPE = 'TRIM' 
    AND wo.STATUS NOT IN ('COMPLETED', 'CANCELLED')
WHERE a.STATUS = 'IN_SERVICE'
  AND ve.CLEARANCE_STATUS IN ('VIOLATION', 'CRITICAL', 'MARGINAL')
ORDER BY TRIM_PRIORITY, ve.DAYS_TO_CRITICAL;

COMMENT ON VIEW VEGETATION_TRIM_PRIORITIES IS 'Prioritized vegetation trimming list based on risk and compliance';

-- ============================================================================
-- PORTFOLIO_KPI_SUMMARY - Executive dashboard KPIs
-- ============================================================================
CREATE OR REPLACE VIEW PORTFOLIO_KPI_SUMMARY AS
SELECT 
    -- Overall Asset Metrics
    COUNT(DISTINCT a.ASSET_ID) AS TOTAL_ASSETS,
    SUM(CASE WHEN a.COMPOSITE_RISK_SCORE >= 80 THEN 1 ELSE 0 END) AS CRITICAL_RISK_COUNT,
    SUM(CASE WHEN a.COMPOSITE_RISK_SCORE >= 60 AND a.COMPOSITE_RISK_SCORE < 80 THEN 1 ELSE 0 END) AS HIGH_RISK_COUNT,
    ROUND(AVG(a.COMPOSITE_RISK_SCORE), 1) AS AVG_PORTFOLIO_RISK,
    
    -- Circuit Metrics
    COUNT(DISTINCT c.CIRCUIT_ID) AS TOTAL_CIRCUITS,
    SUM(c.TOTAL_MILES) AS TOTAL_CIRCUIT_MILES,
    SUM(c.OVERHEAD_MILES) AS OVERHEAD_MILES,
    SUM(c.UNDERGROUND_MILES) AS UNDERGROUND_MILES,
    
    -- Vegetation Metrics
    COUNT(DISTINCT ve.ENCROACHMENT_ID) AS TOTAL_VEG_ENCROACHMENTS,
    SUM(CASE WHEN ve.CLEARANCE_STATUS = 'VIOLATION' THEN 1 ELSE 0 END) AS SPANS_IN_VIOLATION,
    SUM(CASE WHEN ve.CLEARANCE_STATUS = 'CRITICAL' THEN 1 ELSE 0 END) AS SPANS_CRITICAL,
    ROUND(
        100.0 * SUM(CASE WHEN ve.CLEARANCE_STATUS = 'COMPLIANT' THEN 1 ELSE 0 END) / 
        NULLIF(COUNT(DISTINCT ve.ENCROACHMENT_ID), 0), 
    1) AS VEG_COMPLIANCE_RATE,
    
    -- Work Order Metrics
    COUNT(DISTINCT wo.WORK_ORDER_ID) AS TOTAL_WORK_ORDERS,
    SUM(CASE WHEN wo.STATUS = 'COMPLETED' THEN 1 ELSE 0 END) AS COMPLETED_WORK_ORDERS,
    SUM(CASE WHEN wo.STATUS IN ('SUBMITTED', 'APPROVED', 'SCHEDULED', 'IN_PROGRESS') THEN 1 ELSE 0 END) AS OPEN_WORK_ORDERS,
    SUM(wo.MILES_TRIMMED) AS TOTAL_MILES_TRIMMED,
    
    -- Hidden Discovery: Water Treeing
    SUM(CASE WHEN cfp.WATER_TREEING_SEVERITY IN ('MODERATE', 'SEVERE') THEN 1 ELSE 0 END) AS CABLES_WITH_WATER_TREEING,
    SUM(CASE WHEN cfp.WATER_TREEING_SEVERITY = 'SEVERE' THEN 1 ELSE 0 END) AS CABLES_CRITICAL_TREEING,
    
    -- HFTD Exposure
    SUM(CASE WHEN l.FIRE_THREAT_TIER = 'TIER_3' THEN 1 ELSE 0 END) AS ASSETS_IN_TIER_3,
    SUM(CASE WHEN l.FIRE_THREAT_TIER = 'TIER_2' THEN 1 ELSE 0 END) AS ASSETS_IN_TIER_2,
    
    -- Current Date for reference
    CURRENT_DATE() AS AS_OF_DATE

FROM ATOMIC.ASSET a
LEFT JOIN ATOMIC.CIRCUIT c ON a.CIRCUIT_ID = c.CIRCUIT_ID
LEFT JOIN ATOMIC.LOCATION l ON a.LOCATION_ID = l.LOCATION_ID
LEFT JOIN ATOMIC.VEGETATION_ENCROACHMENT ve ON a.ASSET_ID = ve.ASSET_ID
LEFT JOIN ATOMIC.WORK_ORDER wo ON a.ASSET_ID = wo.ASSET_ID
LEFT JOIN ML.CABLE_FAILURE_PREDICTION cfp ON a.ASSET_ID = cfp.ASSET_ID
WHERE a.STATUS = 'IN_SERVICE';

COMMENT ON VIEW PORTFOLIO_KPI_SUMMARY IS 'Executive summary KPIs for portfolio-level dashboard';
